version: '3'

services:
  mysql-container:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=palak135@95
      - MYSQL_DATABASE=spe
      - MYSQL_USER=eshi13
      - MYSQL_PASSWORD=chaos123
  central-hub-container:
    image: central-hub-image
    restart: always
    ports:
      - 9090:9090
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    command: java -jar package.war
    environment:
      - DATABASE_HOST=mysql-container
      - DATABASE_USER=eshi13
      - DATABASE_PASSWORD=chaos123
      - DATABASE_NAME=spe
      - DATABASE_PORT=3306
